title: Alauda Database Service for MySQL-PXC
logoText: Alauda Database Service for MySQL-PXC
lang: zh
api:
  crds:
    - docs/shared/crds/*.yaml
  openapis:
    - docs/shared/openapis/*.json
permission:
  functionresources:
    - docs/shared/functionresources/*.yaml
  roletemplates:
    - docs/shared/roletemplates/*.yaml
